# Override configuration from https://github.com/jenkins-x/jenkins-x-platform/blob/master/values.yaml

PipelineSecrets:

  # lets enable GCR docker builds
  DockerConfig: |-
    {
        "credHelpers": {
            "gcr.io": "gcloud",
            "us.gcr.io": "gcloud",
            "eu.gcr.io": "gcloud",
            "asia.gcr.io": "gcloud",
            "staging-k8s.gcr.io": "gcloud"
        }
    }

# use NodePort for k8s service

jenkins:
  Master:
    ServiceType: NodePort

monocular:
  api:
    service:
      type: NodePort
  ui:
    service:
      type: NodePort
  prerender:
    service:
      type: NodePort
